export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const CREATE_POST_REQUEST = 'CREATE_POSTS_REQUEST'
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const CREATE_POSTS_ERROR = 'CREATE_POSTS_ERROR'

export const EDIT_POSTS_REQUEST = 'EDIT_POSTS_REQUEST'
export const EDIT_POSTS_SUCCESS = 'EDIT_POSTS_SUCCESS'
export const EDIT_POSTS_ERROR = 'EDIT_POSTS_ERROR'

export const DELETE_POSTS_REQUEST = 'DELETE_POSTS_REQUEST'
export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS'
export const DELETE_POSTS_ERROR = 'DELETE_POSTS_ERROR'

export const UPDATE_FILTER_UNIQUE_ID = 'UPDATE_FILTER_UNIQUE_ID'
export const SORT_FROM_ID = 'SORT_FROM_ID'
export const SEARCH_POST = 'SEARCH_POST'

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR'

export const GET_SUMMARY_COVID_INFORMATION_REQUEST = 'GET_SUMMARY_COVID_INFORMATION_REQUEST'
export const GET_SUMMARY_COVID_INFORMATION_SUCCESS = 'GET_SUMMARY_COVID_INFORMATION_SUCCESS'
export const GET_SUMMARY_COVID_INFORMATION_ERROR = 'GET_SUMMARY_COVID_INFORMATION_ERROR'

export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR'

export const GET_CURRENCY_BTC_REQUEST = 'GET_CURRENCY_BTC_REQUEST'
export const GET_CURRENCY_BTC_SUCCESS = 'GET_CURRENCY_BTC_SUCCESS'
export const GET_CURRENCY_BTC_ERROR = 'GET_CURRENCY_BTC_ERROR'

export const GET_CURRENCIES_OF_UKRAINE_REQUEST = 'GET_CURRENCIES_OF_UKRAINE_REQUEST'
export const GET_CURRENCIES_OF_UKRAINE_SUCCESS = 'GET_CURRENCIES_OF_UKRAINE_SUCCESS'
export const GET_CURRENCIES_OF_UKRAINE_ERROR = 'GET_CURRENCIES_OF_UKRAINE_ERROR'

export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST'
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR'

export const GET_DOG_REQUEST = 'GET_DOG_REQUEST'
export const GET_DOG_SUCCESS = 'GET_DOG_SUCCESS'
export const GET_DOG_ERROR = 'GET_DOG_ERROR'

export const GET_CAT_REQUEST = 'GET_CAT_REQUEST'
export const GET_CAT_SUCCESS = 'GET_CAT_SUCCESS'
export const GET_CAT_ERROR = 'GET_CAT_ERROR'
