export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR'

export const CREATE_POST_REQUEST = 'CREATE_POSTS_REQUEST'
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const CREATE_POSTS_ERROR = 'CREATE_POSTS_ERROR'

export const EDIT_POSTS_REQUEST = 'EDIT_POSTS_REQUEST'
export const EDIT_POSTS_SUCCESS = 'EDIT_POSTS_SUCCESS'
export const EDIT_POSTS_ERROR = 'EDIT_POSTS_ERROR'

export const DELETE_POSTS_REQUEST = 'DELETE_POSTS_REQUEST'
export const DELETE_POSTS_SUCCESS = 'DELETE_POSTS_SUCCESS'
export const DELETE_POSTS_ERROR = 'DELETE_POSTS_ERROR'

export const UPDATE_FILTER_UNIQUE_ID = 'UPDATE_FILTER_UNIQUE_ID'
export const SORT_FROM_ID = 'SORT_FROM_ID'
export const SEARCH_POST = 'SEARCH_POST'

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR'




